import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Raleway,Roboto } from "next/font/google";
import { Navbar } from "./components/Navbar/Navbar";
import Footer from "./components/footer/Footer";
import QueryProvider from "./providers/QueryClient";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${raleway.variable} antialiased`}
      >
        <QueryProvider>
        <Navbar />
        {children}
        <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
